development:
  - email: francis@francis.ph
    msisdn: 639389088888

staging: &staging
  - email: francis@francis.ph
    msisdn: 639389088888
  - email: sherwins@rocketmail.com
    msisdn: 639389008888

production:
  *staging